"""Add hidden field to Task

Revision ID: cec5b6cd1823
Revises: c82f5a8701c8
Create Date: 2025-05-20 15:52:10.669298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec5b6cd1823'
down_revision = 'c82f5a8701c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###
